### ISSUE TITLE
Suggestion: use SecureRandom/getInstanceStrong

### ISSUE THREAD

**Issue by claj** [weavejester/crypto-random#9]
When reading up on SecureRandom, the default algorithm is SHA1PRNG. There is a method added in JDK 8 named [`getInstanceStrong`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/SecureRandom.html#getInstanceStrong()), which returns a SecureRandom using some implementation marked as strong, which could be more future proof.

A potentially severe problem with such a change is that a strong SecureRandom algorithm could deplete the platforms entropy source which could lead to severe performance degradation - the PRNG could/should be designed to block until the systems entropy source is repopulated. The default algo on my system is named "NativePRNGBlocking", which will change the guarantees of the library when put under load.

**Comment by weavejester** [comment]
Unless there's an indication that the `SecureRandom` constructor is not secure, and that the insecurity won't be fixed, I think I'd rather keep with the default implementation.

**Comment by claj** [comment]
There certainly **is** an indication that SecureRandom is not secure for a common purpose of this library.

The SHA1PRNG uses a 160 bit state (because that's what SHA-1 do). If I want to generate a strongly random key of, say, 256 bits (like AES-256), the default algorithm SHA1PRNG cannot theoretically generate all the 2^256 combinations that the key should be able to contain, but only about 2^160 of the possible keys.

For any implementation of this algorithm, there can only be 2^160 different keys of 256 bit length, the rest of the states simply cannot be represented in the state space of the PRNG. This is a severe weakness of using the default SecureRandom constructor.

The default SecureRandom is depleted after getting 160 bits from it. For sure, the following bits are certainly hard to guess, but the numbers after the first 160 bits are related to the first bits in a way which makes the generated keys limited in which values they can actually take.

Of course this is somewhat implementation specific (since SHA1PRNG is not a standardised PRNG) but the number of implementations is of course limited.

**Comment by weavejester** [comment]
I'm afraid I don't quite follow your objection. In a PRNG, the number of bytes of entropy is usually less than the number of bytes of output. This doesn't inherently make it insecure.

In any case, it's not the purpose of crypto-random to improve upon the random generation in the JVM already. If you believe there is a flaw in SecureRandom, my suggestion would be to report it as a security issue and get it fixed in the next patch release of Java.
